// Language code -> flag image (round icon ke liye)
export const FLAG_MAP: Record<string, any> = {
  en: require('../assets/flag/english.png'),
  hi: require('../assets/flag/india.png'),
  es: require('../assets/flag/spanish.png'),
  fr: require('../assets/flag/french.png'),
  pt: require('../assets/flag/portuguese.png'),
  ar: require('../assets/flag/arabic.png'),
  ru: require('../assets/flag/russian.png'),
  ko: require('../assets/flag/korean.png'),
  de: require('../assets/flag/german.png'),
  tr: require('../assets/flag/turkish.png'),
  it: require('../assets/flag/italian.png'),
  vi: require('../assets/flag/vietnamese.png'),
  ja: require('../assets/flag/japanese.png'),
  id: require('../assets/flag/indonesian.png'),
  th: require('../assets/flag/thai.png'),
  pl: require('../assets/flag/polish.png'),
  zh: require('../assets/flag/chinese.png'),
  ro: require('../assets/flag/romanian.png'),
  af: require('../assets/flag/afrikaans.png'),
  hu: require('../assets/flag/hungarian.png'),
  uk: require('../assets/flag/ukrainian.png'),
  fil: require('../assets/flag/filipino.png'),
};